apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://172.16.70.57:8001
  name: ilon1
contexts:
- context:
    cluster: ilon1
    namespace: "07"
    user: user7
  name: ilon1-context
- context:
    cluster: ""
    namespace: namespace07
    user: ""
  name: mycluster-context
current-context: ilon1-context
kind: Config
preferences: {}
users:
- name: ilon1-user
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiNjJhMTc5NTg5MDAzZjFmNjgwMTI0MmI0YmQwMmZmYjRhZDc4ZWI3ZSIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoidXNlcjciLCJpc3MiOiJodHRwczovL2lsb24xLmljcDo5NDQzL29pZGMvZW5kcG9pbnQvT1AiLCJhdWQiOiJkMGIwOGIzZGQxYWUzM2FlNWRhNTE1YzQwZGRhYWZlYyIsImV4cCI6MTU1OTE0MjUxNywiaWF0IjoxNTU5MTEzNzE3LCJzdWIiOiJ1c2VyNyIsInRlYW1Sb2xlTWFwcGluZ3MiOlsic3lzdGVtOm1hc3RlcnMiXX0.RmMGMJ7tQUWhz55SSSFKJWDpfyyZJBzfN5QwgSUOOdj4DIuJkHu_8M5_atcdmz3CwUWREZD5u-2PIBbzNoxN01gyrj3eFnWfwtkUG-NeQOZ8ggZpBBCOSi5EFREGutr18vkxCnX3eDS6q4hBbog4X1laZO61yHhOdbGmv9ObH4q35FbwriQg5lF5agk-6_-QEsgJARz2xG1yAUfZMFj8-m6NrML9EJlcaY7zxa1y0z5t_OA-kqHijbTWemH-s9h2jU3Gk9TbPW3jPKdrBNsL8JiEBtwzg6z6_5AKbCZTJ34i7idUd-biErA5sLYpsyKfd-RPHjHS2c9lkzOf4DKaWw
- name: user7
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiZjYwMGI0ZTZiZDMxMmJmYTk1NTQ2ZTg5N2FmMjViOTkwNmJjYWYyZiIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoidXNlcjciLCJpc3MiOiJodHRwczovL2lsb24xLmljcDo5NDQzL29pZGMvZW5kcG9pbnQvT1AiLCJhdWQiOiJkMGIwOGIzZGQxYWUzM2FlNWRhNTE1YzQwZGRhYWZlYyIsImV4cCI6MTU1OTE1NDk3MCwiaWF0IjoxNTU5MTI2MTcwLCJzdWIiOiJ1c2VyNyIsInRlYW1Sb2xlTWFwcGluZ3MiOlsic3lzdGVtOm1hc3RlcnMiXX0.MwDSPsZV86cMyTfmHktR6bNW39fP8Xxca-D1ZV-pO00fAMyoa0aSohU0i6U9RxmJyzOhZpRh-o7Y8xE4RgNqBS9jBFUFq-4_DaGEJPl48YjvDIcXcGzRSaIgGsTBO2yT5ap2l3zTcFYweLOuDCwapOXRVuaDmVmo406uDJ_4yyLHnV-2LVhH4pWXa7_hfnQs6gm5KWulAyGgzDpMas3LXR_72lh2ss7lVeGeM127LuEo3AAJG_dsetGIfIH9A4yRquSKHh0WqyB5snc8yRPrdBFNbjLIHYpA1HHK2UqZgTmsMve5P1P55BzBxSZH594H_W_PGYu3DhPSu-jBs9fObg
